name: GitHub API Tests

on:
  push:
    paths:
      - 'cypress/github-api-tests/**'
  pull_request:
    paths:
      - 'cypress/github-api-tests/**'

jobs:
  github-api:
    runs-on: ubuntu-latest

    env:
      MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./cypress/github-api-tests
        run: npm ci

      - name: Run Cypress tests
        working-directory: ./cypress/github-api-tests
        run: npx cypress run --headless
